[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432

[client]
    ipcPath = ""

[exporter]
    home     = "github.com/vulcanize/vulcanizedb"
    name     = "accountTransformerExporter"
    save     = false
    transformerNames = [
        "account"
    ]
    [exporter.account]
        path = "transformers/account/light/initializer"
        type = "eth_contract"
        repository = "github.com/vulcanize/account_transformers"
        migrations = "db/migrations"
        rank = "0"
